from setuptools import setup, find_packages

def readme():
    with open('README.md') as f:
        return f.read()

setup(name = 'WaveBlocksND',
      version = '0.5',
      description = u'Reusable building blocks for simulations with semiclassical wavepackets.',
      long_description = readme(),
      author = 'R. Bourquin',
      author_email = 'raoul.bourquin@sam.math.ethz.ch',
      url = 'https://github.com/WaveBlocks/WaveBlocksND',
      packages = find_packages(),
      classifiers = [
        'Development Status :: 4 - Beta',
        'Topic :: Scientific/Engineering :: Mathematics',
        'Topic :: Scientific/Engineering :: Physics',
        'Topic :: Scientific/Engineering :: Chemistry',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Environment :: Console',
        'Programming Language :: Python :: 2.7',
      ],
      license = 'BSD',
      install_requires = [
        'h5py >= 2.4.0',
        'matplotlib >= 1.4.3',
        #'mayavi',
        'numpy >= 1.9.2',
        'scipy >= 0.14.1',
        'sympy >= 0.7.6',
      ],
      scripts = [
        'scripts/scripts/Batch.py',
        'scripts/scripts/ComputeAutocorrelation.py',
        'scripts/scripts/ComputeAutocorrelationNET.py',
        'scripts/scripts/ComputeEigenstates.py',
        'scripts/scripts/ComputeEnergies.py',
        'scripts/scripts/ComputeEnergiesCAN.py',
        'scripts/scripts/ComputeEnergiesNET.py',
        'scripts/scripts/ComputeEvaluateWavepacketsCanonical.py',
        'scripts/scripts/ComputeEvaluateWavepacketsEigen.py',
        'scripts/scripts/ComputeNorms.py',
        'scripts/scripts/ComputeNormsNET.py',
        'scripts/scripts/ComputeTransformToEigen.py',
        'scripts/scripts/ConfigurationGenerator.py',
        'scripts/scripts/DeleteWavefunction.py',
        'scripts/scripts/EigenstatesFlipSign.py',
        'scripts/scripts/ForAll.py',
        'scripts/scripts/Main.py',
        'scripts/plotters/PlotAutocorrelations.py',
        'scripts/plotters/PlotEnergies.py',
        'scripts/plotters/PlotNorms.py',
        'scripts/plotters/PlotPotential1D.py',
        'scripts/plotters/PlotPotential2D.py',
        'scripts/plotters/PlotWavefunction1D.py',
        'scripts/plotters/PlotWavefunction2Dcontour.py',
        'scripts/plotters/PlotWavefunction2Dsurface.py',
        'scripts/plotters/PlotWavepacket1D.py',
        'scripts/plotters/PlotWavepacket2Dcontour.py',
        'scripts/plotters/PlotWavepacketCoefficients.py',
        'scripts/plotters/PlotWavepacketCoefficientsMap.py',
        'scripts/plotters/PlotWavepacketCoefficientsMapEigen.py',
        'scripts/plotters/PlotWavepacketCoefficientsStem.py',
        'scripts/plotters/PlotWavepacketParameters1D.py',
        'scripts/plotters/PlotWavepacketParametersDD.py',
        'scripts/plotters/PlotWavepacketParametersSchema2D.py',
        'scripts/plotters/PlotWavepacketParametersTrajectory2D.py'
      ])
